<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DouyinTTS.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.30" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.4.5" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.4.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Live\Protocol\sign.js" />
  </ItemGroup>

</Project>
